[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build.env]
NIXPACKS_BUILDER = "nodejs"